version: '3.8'
services:
  db:
    image: postgres:15.4
#    command: ["sh", "-c", "chown -R nginx:nginx /code/static/"]
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_value:/code/static/
    depends_on:
      - web


volumes:
  static_value:
  postgres_data: